##Lets Import the necessary libraries

In [ ]:
#lets import them
import pandas as pd
import tensorflow as tf
import numpy as np

In [ ]:
tf.__version__

'2.12.0'

In [ ]:
#lets load the dataset
df=pd.read_csv('/content/sample_data/Churn_Modelling.csv')
df

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [ ]:
#lets now split the independent(x) and dependent(y) based on the problem given
x=df.iloc[:,3:-1].values
y=df.iloc[:,-1].values
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [ ]:
#In the x set we have datas both in numbers and categories so we need to convert the gender and country column in numbers
#so for gender we have only two male and female so we can use LabelEncoder
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x[:, 2]=le.fit_transform(x[:, 2])

In [ ]:
x[:, 2]

array([0, 0, 0, ..., 0, 1, 0], dtype=object)

In [ ]:
from math import remainder
#now lets encode the country column since it has more than two we use onehotencoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
x=np.array(ct.fit_transform(x))
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [ ]:
x[:, 1]

array(['France', 'Spain', 'France', ..., 'France', 'Germany', 'France'],
      dtype=object)

In [ ]:
#lets split the dataset into training and testing
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:
#now the next import step in the deep learning is to perform feature scaling for both training and testing datasets
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)


In [ ]:
x_train

array([[-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
        -1.03227043,  0.32472465]])

## Building the ANN


In [ ]:
#lets build the ANN
ann=tf.keras.models.Sequential()

In [ ]:
"""
Here totally we have three layers input layer, hidden layer, output layer
"""
#lets add the input layer
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [ ]:
#lets add the second hidden layer
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [ ]:
#lets add the third hidden layer
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [ ]:
#now lets add the output layer
#since the output layer contains only binary values so we need only one neuron
"""
if the output layer contains more than two say A,B,C then we need to create 3 neurons for A as it will be (1,0,0) , B(0,1,0) C(0,0,1)
here in this case we are predicting for binary thats why we are using sigmoid but in the case of three variables we have to use soft max
"""
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

In [ ]:
#now the next step is to compile the ANN
"""
so here the optimizer is the stochastic gradient decent and loss is binay_crossentropy
as since we have the binary outcome we use binary_crossentropy
we have multiple outcomes then we ue crossentropy_loss (categories)
metrics need to be given in list as several parameters can be passed in the metrics section at a time
"""
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
#lets train the ANN
ann.fit(x_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3367 - accuracy: 0.8605
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3337 - accuracy: 0.8626
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3340 - accuracy: 0.8620
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3336 - accuracy: 0.8648
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3340 - accuracy: 0.8620
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3338 - accuracy: 0.8620
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3345 - accuracy: 0.8609
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3341 - accuracy: 0.8644
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3346 - accuracy: 0.8624
Epoch 10/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3341 - accura

In [ ]:
len(x_train)

8000

In [ ]:
8000/32

250.0

## Lets start predicting the ANN using the given example:-
1. Geography: france
2. Credit Score:600
3. Gender: male
4. Age:40 years old
5. tenure: 3 years old
6. balance: 600000
7. number of products: 2
8. does this customer have a credit card: yes
9. customer is an active member: yes
10. estimated salary: 50000
#### so check whether we need to say goodbye to the customer ?

In [ ]:

if ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]])) > 0.8:
  print('Customer will leave the bank')
else:
  print('Customer will not leave the bank')

1/1 [==============================] - 0s 106ms/step
Customer will not leave the bank


In [ ]:
#predicting the test results
y_pred=ann.predict(x_test)

63/63 [==============================] - 0s 3ms/step


In [ ]:
#as mentioned above criteria
y_pred=(y_pred>0.9)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [ ]:
#lets check the confusion matrix, and accuracy_score
from sklearn.metrics import accuracy_score,confusion_matrix
print(confusion_matrix(y_pred,y_test))
accuracy_score(y_pred,y_test)

[[1594  396]
 [   1    9]]


0.8015